package ch.cs.eb.ipa.model;

/**
 * author: Elijon Berisha
 * date: 10.03.2022
 * class: UserAuthority.java
 */

// CONTAINS ALL USER ROLE NAMES
public enum UserAuthority {
    /*
    INACTIVE = USER CAN LOG IN BUT NEEDS TO BE ADMITTED TO USE FUNCTIONALITIES
    EMPLOYEE = NORMAL USER; USER CAN ACCESS FUNCTIONALITIES BUT IS NOT AN ADMIN
    ADMIN = INHERITS THE NORMAL USER ACCESS RIGHTS; CAN ADMIT NEW USERS AND CHANGE THEIR PASSWORDS
     */
    INACTIVE, EMPLOYEE, ADMIN
}
